/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package boutque;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class adddresses extends javax.swing.JFrame {

Connection con;
Statement stmt;
ResultSet rs;
int curRow = 0;
/**
     
     */
    public adddresses() {
        initComponents();
        //DoConnect();
    }
    public void DoConnect( ) {
    try{
     
     String host= "jdbc:derby://localhost:1527/boutque";
     String uName="abc";
     String uPass="123";

     con = DriverManager.getConnection(host,uName,uPass);
     stmt = con.createStatement( ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
     String SQL = "SELECT * FROM DRESSDATABASE";
     rs = stmt.executeQuery( SQL );

     while(rs.next( )){
    int id_col = rs.getInt("SERIALNO");
   
    String size = rs.getString("SIZE");
    String color = rs.getString("color");
    String costprice = rs.getString("costprice");
    String saleprice = rs.getString("saleprice");
    String gender=rs.getString("gender");
    Double discountrate=rs.getDouble("discountrate");
    String dr=Double.toString(discountrate);
    int comid=rs.getInt("companyid");
    String id = Integer.toString(comid);
    
    
    textserialno.setText(id);
    textsize.setText(size);
    textcolor.setText(color);
    textcostprice.setText(costprice);
    textsale.setText(saleprice);
    textdiscountrate.setText(dr);
    textgender.setText(gender);
    textcompanyid.setText(dr);
   
    
    }
    
    }
  


     catch (Exception err ) {
     System.out.println( err.getMessage( ) );
     }


    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textserialno = new javax.swing.JTextField();
        textsize = new javax.swing.JTextField();
        textcolor = new javax.swing.JTextField();
        textcostprice = new javax.swing.JTextField();
        textsale = new javax.swing.JTextField();
        textdiscountrate = new javax.swing.JTextField();
        textgender = new javax.swing.JTextField();
        textcompanyid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        SaveRecord = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        NewRecord = new javax.swing.JButton();
        CancelRecord = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 51));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        textserialno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textserialnoActionPerformed(evt);
            }
        });

        textcolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textcolorActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 51, 51));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("serial no :");

        jLabel2.setBackground(new java.awt.Color(0, 51, 51));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("size :");

        jLabel3.setBackground(new java.awt.Color(0, 51, 51));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("color :");

        jLabel4.setBackground(new java.awt.Color(0, 51, 51));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("costprice :");

        jLabel5.setBackground(new java.awt.Color(0, 51, 51));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("saleprice :");

        jLabel6.setBackground(new java.awt.Color(0, 51, 51));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("discountrate:");

        jLabel7.setBackground(new java.awt.Color(0, 51, 51));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("gender");

        jLabel8.setBackground(new java.awt.Color(0, 51, 51));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("company ID");

        SaveRecord.setText("Save new Record");
        SaveRecord.setEnabled(false);
        SaveRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveRecordActionPerformed(evt);
            }
        });

        jButton2.setText("BACK");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        NewRecord.setText("New record");
        NewRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewRecordActionPerformed(evt);
            }
        });

        CancelRecord.setText("Cancel New Record");
        CancelRecord.setEnabled(false);
        CancelRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelRecordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(NewRecord)
                        .addGap(26, 26, 26)
                        .addComponent(CancelRecord)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SaveRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textserialno)
                            .addComponent(textsize)
                            .addComponent(textcolor)
                            .addComponent(textcostprice)
                            .addComponent(textsale)
                            .addComponent(textdiscountrate)
                            .addComponent(textgender)
                            .addComponent(textcompanyid, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textserialno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textsize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textcolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textcostprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textsale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textdiscountrate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textcompanyid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveRecord)
                    .addComponent(CancelRecord)
                    .addComponent(NewRecord))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textserialnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textserialnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textserialnoActionPerformed

    private void textcolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textcolorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textcolorActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
    this.setVisible(false);
    adminmenu ad= new adminmenu();
    ad.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void NewRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewRecordActionPerformed
       
            try {
                curRow = rs.getRow( );
            
           
           textserialno.setText("");
           textsize.setText("");
           textcolor.setText("");
            textcostprice.setText("");
            textsale.setText("");
            textdiscountrate.setText("");
            textgender.setText("");
            textcompanyid.setText("");
       
         NewRecord.setEnabled( false );
         SaveRecord.setEnabled( true );
         CancelRecord.setEnabled( true ); 
            }
     
     catch (SQLException ex) {
                Logger.getLogger(adddresses.class.getName()).log(Level.SEVERE, null, ex);
            }// TODO add your handling code here:
    }//GEN-LAST:event_NewRecordActionPerformed

    private void CancelRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelRecordActionPerformed
        try {
            curRow = rs.getRow( );
            textserialno.setText("");
            textsize.setText("");
            textcolor.setText("");
            textcostprice.setText("");
            textsale.setText("");
            textdiscountrate.setText("");
            textgender.setText("");
            textcompanyid.setText("");
         
        NewRecord.setEnabled( true );

        SaveRecord.setEnabled( false );
        CancelRecord.setEnabled( false );
         
            
            
        } catch (SQLException ex) {
            Logger.getLogger(adddresses.class.getName()).log(Level.SEVERE, null, ex);
        }
            
           
          
       
     
         
     
     
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelRecordActionPerformed

    private void SaveRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveRecordActionPerformed
      String SerialNo =textserialno.getText();
      String Size=textsize.getText();
      String Color=textcolor.getText(); 
      String CostPrice =textcostprice.getText();
      int CP = Integer.parseInt(CostPrice);
      String SalePrice=textsale.getText();
      int SP = Integer.parseInt(SalePrice);
      String Discountrate=textdiscountrate.getText();
      double DR = Integer.parseInt(Discountrate);
      String Gender =textgender.getText();
      String Companyid=textcompanyid.getText();
        
      
      
   try {
    rs.moveToInsertRow( );
    rs.updateString("SERIALNO", SerialNo);
    rs.updateString("SIZE", Size);
    rs.updateString("COLOR", Color);
    rs.updateInt("COSTPRICE", CP);
    rs.updateInt("SALEPRICE", SP);
    rs.updateDouble("DISCOUNTRATE", DR);
    rs.updateString("GENDER", Gender);
    rs.updateString("COMPANYID", Companyid);
    rs.updateString("SEARCHSERIAL", SerialNo);
    rs.insertRow( );
    
    stmt.close( );
    rs.close( );
    
    
    stmt = con.createStatement( ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
     String SQL = "SELECT * FROM DRESSDATABASE";
     rs = stmt.executeQuery( SQL );

     while(rs.next( )){
    int id_col = rs.getInt("SERIALNO");
    String s = Integer.toString(id_col);
   
    String size = rs.getString("SIZE");
    String color = rs.getString("color");
    String costprice = rs.getString("costprice");
    String saleprice = rs.getString("saleprice");
    String gender=rs.getString("gender");
    Double discountrate=rs.getDouble("discountrate");
    String dr=Double.toString(discountrate);
    int comid=rs.getInt("companyid");
    String id = Integer.toString(comid);
    
    textserialno.setText(s);
    textsize.setText(size);
    textcolor.setText(color);
    textcostprice.setText(costprice);
    textsale.setText(saleprice);
    textgender.setText(gender);
    textdiscountrate.setText(dr);
    textcompanyid.setText(id);

     
        NewRecord.setEnabled( true );
        SaveRecord.setEnabled( false );
        CancelRecord.setEnabled( false );

      
        } }
catch (SQLException err) {
          System.out.println(err.getMessage());
        }

    
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveRecordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adddresses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adddresses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adddresses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adddresses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adddresses().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelRecord;
    private javax.swing.JButton NewRecord;
    private javax.swing.JButton SaveRecord;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textcolor;
    private javax.swing.JTextField textcompanyid;
    private javax.swing.JTextField textcostprice;
    private javax.swing.JTextField textdiscountrate;
    private javax.swing.JTextField textgender;
    private javax.swing.JTextField textsale;
    private javax.swing.JTextField textserialno;
    private javax.swing.JTextField textsize;
    // End of variables declaration//GEN-END:variables
}
