/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package boutque;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class UPDATERECORD extends javax.swing.JFrame {
Connection con;
Statement stmt;
ResultSet rs;
    /**
     * Creates new form UPDATERECORD
     */
    public UPDATERECORD() {
        initComponents();
        //DoConnect();
   
    }
   public void DoConnect(int ser) {
    try{
    
     String host= "jdbc:derby://localhost:1527/boutque";
     String uName="abc";
     String uPass="123";

     con = DriverManager.getConnection(host,uName,uPass);
     stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);

     String SQL1 = "select * from DRESSDATABASE";
      rs = stmt.executeQuery( SQL1 );
           //TextSerialNumber
     
     while(rs.next( )){
         
        int id_col = rs.getInt("serialno");
        if(id_col == ser)
        {
         
         String serialno = Integer.toString(id_col);
         String size = rs.getString("size");
         String color = rs.getString("color");
         double cp = rs.getDouble("costprice");
         String costprice=Double.toString(cp);
         double sp=rs.getDouble("saleprice");
         String saleprice=Double.toString(sp);
         double dr=rs.getDouble("discountrate");
         String discountrate=Double.toString(dr);
         String gender=rs.getString("gender");
         int cid=rs.getInt("companyid");
         String companyid=Integer.toString(cid); 
    
    textserialno.setText(serialno);
    textsize.setText(size);
    textcolor.setText(color);
    textcostprice.setText(costprice);
    textsaleprice.setText(saleprice);
    textgender.setText(gender);
    textdiscountrate.setText(discountrate);
    textcompanyid.setText(companyid);
        }

       }
     
    rs.close();
    
    }  catch (Exception err ) {
     System.out.println( err.getMessage( ) );
     }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textserialno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textsize = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textcolor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textcostprice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textsaleprice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textdiscountrate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textgender = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textcompanyid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("serialno:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("size:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("color:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("costprice:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("saleprice:");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("discountrate:");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("gender:");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("companyid:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textserialno)
                            .addComponent(textsize)
                            .addComponent(textcolor)
                            .addComponent(textcostprice, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                        .addGap(82, 82, 82)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textsaleprice)
                                    .addComponent(textdiscountrate)
                                    .addComponent(textgender, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textcompanyid, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textserialno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(textsaleprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textsize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(textdiscountrate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textcolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(textgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textcostprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(textcompanyid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
   try
   {
     String host= "jdbc:derby://localhost:1527/boutque";
     String uName="abc";
     String uPass="123";

     con = DriverManager.getConnection(host,uName,uPass);
     stmt = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
     String SQL1 = "select * from DRESSDATABASE";
     rs = stmt.executeQuery( SQL1 );
    
  
   

    String serial=textserialno.getText();
    int serialno=Integer.parseInt(serial);
    String size=textsize.getText();
    String color=textcolor.getText();
    String cp=textcostprice.getText();
    double costprice=Double.parseDouble(cp);
    String sp=textsaleprice.getText();
    double saleprice=Double.parseDouble(sp);
    String dr=textdiscountrate.getText();
    double discountrate=Double.parseDouble(dr);
    String gender = textgender.getText();
    String CId=textcompanyid.getText();
    int compid=Integer.parseInt(CId);
    
    //String SQL1 = "update  ABC.DRESSDATABASE set size = ' "+size+" ',color = ' " +color+ " ',costprice = ' " +costprice+ " ',saleprice = ' " +saleprice+ " ',discountrate = ' " +discountrate+ " ',gender = ' " +gender+ " ',companyid = ' " +compid+" where serialno = '" +serialno+" ' ";
    
    //JOptionPane.showInputDialog(null,"Updated");
     // String SQL1 = "UPDATE  ABC.DRESSDATABASE";
      //rs = stmt.executeQuery( SQL1 );
        while(rs.next())
    {
        int id_col = rs.getInt("SERIALNO");
        if(id_col == serialno)
        { 
//rs.updateInt( "SERIALNO", serialno );
rs.updateString( "SIZE", size );
rs.updateString( "COLOR", color );
rs.updateDouble( "COSTPRICE", costprice );
rs.updateDouble( "SALEPRICE", saleprice );
rs.updateDouble( "DISCOUNTRATE", discountrate );
rs.updateString( "GENDER", gender );
rs.updateInt( "COMPANYID", compid );
rs.updateRow( );
JOptionPane.showMessageDialog(null,"Updated");
//rs.close();
   
   }}
      rs.close();
}
catch (SQLException err) {
System.out.println(err.getMessage() );
}
    this.setVisible(false);
    MainMenu mm = new MainMenu();
    mm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UPDATERECORD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UPDATERECORD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UPDATERECORD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UPDATERECORD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UPDATERECORD().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textcolor;
    private javax.swing.JTextField textcompanyid;
    private javax.swing.JTextField textcostprice;
    private javax.swing.JTextField textdiscountrate;
    private javax.swing.JTextField textgender;
    private javax.swing.JTextField textsaleprice;
    private javax.swing.JTextField textserialno;
    private javax.swing.JTextField textsize;
    // End of variables declaration//GEN-END:variables
}
